// src/app/api/cafes/route.ts

import { NextResponse } from "next/server";
import { readFileSync } from "fs";
import { join } from "path";
import { fetchCafesFromOverpass } from "@/lib/overpass";
import { FALLBACK_CAFES } from "@/lib/fallback-cafes";

// Serve from the pre-generated static file when present — instant, no Overpass query.
// The file is generated by: node scripts/fetch-cafes.mjs
function readStaticCache(): unknown[] | null {
  try {
    const raw = readFileSync(join(process.cwd(), "public", "cafes-cache.json"), "utf8");
    const { cafes } = JSON.parse(raw);
    if (Array.isArray(cafes) && cafes.length > 0) return cafes;
  } catch {
    // file missing or unreadable — fall through to Overpass
  }
  return null;
}

// In-memory cache as a secondary layer (avoids repeated disk reads)
let memCafes: unknown[] | null = null;

export async function GET() {
  if (memCafes) {
    return NextResponse.json({ cafes: memCafes, source: "cache" });
  }

  const staticCafes = readStaticCache();
  if (staticCafes) {
    memCafes = staticCafes;
    return NextResponse.json({ cafes: staticCafes, source: "static" });
  }

  try {
    const cafes = await fetchCafesFromOverpass();
    if (cafes.length === 0) {
      return NextResponse.json({ cafes: FALLBACK_CAFES, source: "fallback" });
    }
    memCafes = cafes;
    return NextResponse.json({ cafes, source: "overpass" });
  } catch (error) {
    console.error("Overpass API error:", error);
    return NextResponse.json(
      { cafes: FALLBACK_CAFES, source: "fallback", error: "Overpass API unavailable" },
      { status: 200 },
    );
  }
}
